bug: wrong place for env variable in cloudflare workflow

diff --git a/.github/workflows/deploy-cloudflare-worker.yaml b/.github/workflows/deploy-cloudflare-worker.yaml
--- a/.github/workflows/deploy-cloudflare-worker.yaml
+++ b/.github/workflows/deploy-cloudflare-worker.yaml
@@ -41,6 +41,7 @@ jobs:
     secrets: inherit
 
   build:
+    needs: create-env
     runs-on: ubuntu-latest
 
     steps:
@@ -95,34 +96,21 @@ jobs:
           fi
 
       - name: Set Wrangler secrets in bulk from secrets.json
+        env:
+            CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
+            CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
         run: |
+          # Check if secrets.json exists and is valid JSON
+          if [ ! -f apps/merchant/secrets.json ]; then
+            echo "secrets.json file not found in decrypted artifact"
+            exit 1
+          fi
           cd apps/merchant
           npx wrangler secret bulk < secrets.json
 
-      - name: Create an encrypted artifact with .env and wrangler.jsonc with CRYPTOKEN for debugging
-        run: |
-          tar -czf env_and_wrangler.tar.gz .env apps/merchant/wrangler.jsonc
-          echo "env_and_wrangler.tar.gz created with .env and wrangler.jsonc"
-          ls -l env_and_wrangler.tar.gz
-          echo "Encrypting env_and_wrangler.tar.gz with CRYPTOKEN"
-          openssl enc -aes-256-cbc -salt -in env_and_wrangler.tar.gz -out env_and_wrangler.tar.gz.enc -iter 10000  -pass pass:"${{ secrets.CRYPTOKEN }}"
-          echo "Encrypted file env_and_wrangler.tar.gz.enc created"
-          rm env_and_wrangler.tar.gz
-          ls -l env_and_wrangler.tar.gz.enc
-          echo "decrypt with: openssl enc -aes-256-cbc -d -salt -in env_and_wrangler.tar.gz.enc -out env_and_wrangler.tar.gz -iter 10000 -pass pass:\"<CRYPTOKEN  value>\""
-
-      - name: Upload shared encrypted artifact
-        uses: actions/upload-artifact@v6
-        with:
-          name: encrypted-env
-          include-hidden-files: true
-          path: env_and_wrangler.tar.gz.enc
           
       - name: Deploy
         uses: cloudflare/wrangler-action@v3
-        env:
-          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
-          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
         with:
           apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
           accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
